### ISSUE TITLE
R function gds2fasta generates switched sequence?

### ISSUE THREAD

**Issue by dandaman** [thlee/SNPhylo#14]
Hi,

I am reusing some of your code from generate_snp_sequence.R to extract LD-filtered sequences for haploid data.

I'm currently wondering whether you have a bug in your code or whether snprelate simply produces different results for diploid and haploid data. 

In your function gds2fasta you get the allele sequence using this call in line 

195: rep.allele <- do.call(rbind, strsplit(read.gdsn(index.gdsn(gdsobj, "snp.allele"))[snp.idx], "/", fixed = TRUE))

In my hands this results in a vector where [1] is the REF and [2] is the ALT, consistent with what is written in the snprelate docs.

If this is also the case for diploid data, then you have mixed REF and ALT when you index rep.allele[j,XX] in lines 208-223. I.e. rep.genotype[i,j] == 0 should be REF ergo seq[j] <- rep.allele[j,1] and not seq[j] <- rep.allele[j,2].

I have tested toe routine based on my data (generated by freebayes) and ,1 is the REF while,2 is the ALT allele. 

What do you think?

Best,
Daniel

**Comment by thlee** [comment]
Hi Daniel,

In the program, a heterogeneous SNP in a diploid organism is converted to an  IUB/IUPAC nucleic acid code so, in my opinion, the switching between the bases is not a bug in the script. :)

Best,

Tae-Ho Lee

**Comment by dandaman** [comment]
You are right. I was not aware that the input in your case is not VCF and thus the genotype codes have different meaning... Sorry.
