### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by stly1996** [thlee/SNPhylo#24]
When I running SNPhylo with snphylo.sh -v VCF_file in Linux

appear the follow error message

Traceback (most recent call last):
  File "/root/SNPhylo/scripts/remove_low_depth_genotype_data.py", line 49, in <module>
    format_col = vcf_data[8].split(':')
IndexError: list index out of range

my file format is
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  CX368 ...
01      1131    .       T       C       12.77   LowQual  (omitted)    GT:PL:DP:GQ:AD   T  ...
01      1132    .       A       G       12.77   LowQual  (omitted)    GT:AD:GQ:PL:DP   A  ...
each line Separated with tab

How can I do?

**Comment by birsandhu** [comment]
I have similar issue: 
format_col = vcf_data[8].split(':')
IndexError: list index out of range
Please let me know the solution for this. Thanks!

**Comment by IainPerry** [comment]
I had same issue, but it was because it wont run on zipped files. Unzipping my vcf allowed it to work.

**Comment by lly1214** [comment]
I met the same error. Have you resolved it?
